### ISSUE TITLE
大佬，这个怎么用啊

### ISSUE THREAD

**Issue by yishengyouli** [Caterpolaris/sign#1]
大佬，可否添加一手好友QQ：2657618341

**Comment by Caterpolaris** [comment]
## 用青龙面板定时执行 [地址](https://github.com/whyour/qinglong)
1. 创建订阅
![image](https://github.com/Caterpolaris/sign/assets/125627865/a0c9e4c2-a7fe-4991-aa01-9f0a0091f019)
2. 添加对应要签到的环境变量（抓app的数据包获取),安装环境依赖 `requests`
![image](https://github.com/Caterpolaris/sign/assets/125627865/33fb68d5-0a8f-471b-9785-78f3e0064611)
3. 创建定时任务
![image](https://github.com/Caterpolaris/sign/assets/125627865/3972ceec-29f5-499c-92a6-9b721bc85058)

## 直接写个定时执行的程序每次启动`python run.py`

**Comment by yishengyouli** [comment]
感谢大佬！！
